spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none
  defer-datasource-initialization: true
  datasource:
    url:jdbc:h2:mem: testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  issuer: yjj1544@gmail.com
  secretKey: amluNDA0MQ==

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true