CREATE TABLE USERS (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nick_name VARCHAR(30),
                       email VARCHAR(50) NOT NULL UNIQUE,
                       password VARCHAR(60) NOT NULL,
                       created_at TIMESTAMP,
                       image VARCHAR(255),
                       role VARCHAR(255),
                       refresh_token VARCHAR(255),
                       journal_count BIGINT,
                       last_healing_program VARCHAR(255),
                       last_healing_date VARCHAR(255),
                       active BOOLEAN
);

